title: Nahomi Ichino
description: 
  Associate Professor of Political Science, Emory University
  | Trainings Director, Evidence in Governance and Politics
show_downloads: false
theme: jekyll-theme-minimal
